
#' Assign population attributable fractions to diseases
#' 
#' Look at the data fields generated by running [hesr::findEpisodes()] 
#' and create a parallel set of data fields containing the 
#' corresponding population attributable fractions. 
#' 
#' Population attributable fractions can be stratified by 
#' "year", sex", "ageband" and/or "imd_quintile".
#'
#' @param data Data table - episode-level hospital episode statistics data.
#' @param paf_data Data table - the population attributable fractions to 
#' be assigned to diseases.
#' @param paf_strat Character vector - the variables by which the 
#' population attributable fractions are stratified.
#' @param col_name_vec Character vector - The name of the diagnosis code columns
#' scanned to identify target disease diagnosis codes.
#'
#' @return Returns the input episode-level hospital episode statistics data 
#' with new columns added for the population attributable fractions 
#' that correspond to the tobacco and/or alcohol related diseases identified 
#' in each of the diagnosis columns.
#' 
#' @importFrom data.table :=
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' 
#' 
#' }
#' 
assignPAFs <- function(
    data,
    paf_data = hesr::paf_data,
    paf_strat = c("ageband", "sex", "imd_quintile"),
    col_name_vec = c("diag_01")
) {
  
  ###################################
  # loop through inputs
  # adding a new column to the dataset each time
  
  for(cn in 1:length(col_name_vec)) {
    
    # cn <- 1
    
    col_name <- col_name_vec[cn]
    
    # Create a new column name
    cn_store <- paste0(col_name, "_PAF")
    
    ##############################
    # Get the reference condition names
    data[, condition := get(paste0(col_name, "_icdFlag"))]
    
    ##############################
    # Merge the population attributable fractions with the HES data
    data <- merge(data, paf_data, by = unique(c("condition", paf_strat)), 
                  all.x = TRUE, all.y = FALSE, sort = FALSE)
    
    ##############################
    # Store the PAF estimates in an appropriately names data field
    
    setnames(data, "PAF", cn_store)
    
    # Delete the working columns
    data[ , condition := NULL]
    
    
    rm(cn_store)
    
  }
  
  return(data)
}
